### ISSUE TITLE
Is this project still under active development?

### ISSUE THREAD

**Issue by AncientSwordRage** [dwmkerr/crosswords-js#11]
I'm trying to find all the javascript crossword packages to assess which is the best one to contribute to.

Is this still under active development?

**Comment by dwmkerr** [comment]
Hi @AncientSwordRage - I haven't updated it for a while but would certainly be happy to increase the feature set or work on it if it seems people are finding it useful! I like the idea of a general purpose, pure JavaScript approach to managing and rendering crosswords (which can then be wrapped in React, Vue, etc as needed!)

**Comment by dwmkerr** [comment]
FYI update here that there's new development actively happening at the moment, first on developer experience but also fixing some of the bugs and modernising the code-base, keep an eye on PRs as they come in and the CHANGELOG as it is growing!
