### ISSUE TITLE
demo doesn't seem to be working!

### ISSUE THREAD

**Issue by mmkal** [dwmkerr/crosswords-js#35]
Hi! This looks very nice - but I tried to play around with it and the github pages site doesn't seem to render anything (other than the word "AcrossDown" - a clue??)

<img width="1183" alt="image" src="https://github.com/dwmkerr/crosswords-js/assets/15040698/bed52faf-a6ce-4c1b-a3fe-9562ca51ad93">

**Comment by dwmkerr** [comment]
Working on it at the moment! There's a big fix on the way that should also fix this, it's PR #34 at the moment

**Comment by mmkal** [comment]
Oh great, thank you! I was also able to get it running locally. Will close this and watch that PR!
