### ISSUE TITLE
Is there any way to highlight mistakes?

### ISSUE THREAD

**Issue by mnvx** [dwmkerr/crosswords-js#9]
Thanks for so handy implementation of crosswords.

May you are point me how to highlight mistakes in filled crossword?

**Comment by pvspain** [comment]
Hi @mvnx,
I've recently started contributing to this project.
The feature you describe is not currently supported, but it's something I'd like to see in the future too!
@dwmkerr has highlighted the things he'd like worked on as a priority in the README in the root of the repo.

**Comment by dwmkerr** [comment]
Thanks @pvspain for your notes! @mnvx this is a great idea, let me bump it to the top of the list of things for us to work on :)

By the way, is there anything else you've seen in the code / documentation that you could see as an improvement for the developer experience or the crossword component itself?

**Comment by mnvx** [comment]
Hi. Thanks for your replies. I asked this question about 2 years ago and currently, the project where we used the crosswords component, has already been completed and I do not know about its destiny. For this reason, the issue is not actual for me. Thanks anyway.

**Comment by dwmkerr** [comment]
No worries will close the issue!
